# Generated by Django 4.2.6 on 2023-10-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_machine_worker_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="worker",
        ),
        migrations.AddField(
            model_name="machine",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="machines", to="customers.worker"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="worker_names",
            field=models.TextField(blank=True),
        ),
    ]
