# Generated by Django 4.2.6 on 2023-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_remove_machine_worker_machine_workers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="machine", to="customers.worker"
            ),
        ),
    ]
